### ISSUE TITLE
Prettier ignores prettier_flags when using github-pr-review

### ISSUE THREAD

**Issue by paulvanbrenk** [EPMatt/reviewdog-action-prettier#37]
This is how I configured the action in my workflow file
```
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # add comments in the review
          level: warning # [info,warning,error]
          prettier_flags: '**/*.{js,ts,tsx,md,json}'
```
However in the log from the github action I see the following:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/5273975/223493557-4d55aa4a-e501-4fc0-b7dd-2058ae0b4a51.png">

And I get suggestions for changes in the yarn.lock file.

Any ideas? 

edit: created a repo to show the issue. You can see the errors reported in the logs for the workflow for this PR

https://github.com/paulvanbrenk/prettier-action/pull/1
