### ISSUE TITLE
Check mode: only file filter is supported

### ISSUE THREAD

**Issue by bmulholland** [EPMatt/reviewdog-action-prettier#70]
Prettier check outputs only a file name, no line or column number, so filter mode of e.g. added will not work. This action will happily try, though, and then the reports will be filtered out by reviewdog.

**Comment by hobbes3** [comment]
Are you talking about `reporter: github-check`?

I found out when using this flag for push that this action doesn't check any files (even with `filter_mode: nofilter`) and always passes. I ended up having to do a normal `npx prettier --check .` for push like this:

```yaml
prettier:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v7
    - if: github.event_name == 'pull_request'
      uses: EPMatt/reviewdog-action-prettier@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_level: warning
    - if: github.event_name != 'pull_request'
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: npm
    - if: github.event_name != 'pull_request'
      run: |
        npm ci
        npx prettier --check .
```

Whereas for all the other Reviewdog actions I've tried, something like this works fine for both push and pull (meaning it'll show errors in the annotation for push and the normal comments in the PR):

```yaml
stylelint:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v7
    - uses: reviewdog/action-stylelint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
        stylelint_inputs: "css/**/*.css"
        fail_level: warning
```
