### ISSUE TITLE
Input 'fail_on_error' has been deprecated with message: Deprecated, use `fail_level` instead.

### ISSUE THREAD

**Issue by kenorb** [EPMatt/reviewdog-action-prettier#72]
```
Run EPMatt/reviewdog-action-prettier@v1
  with:
    github_token: ***
    level: error
    reporter: github-pr-review
    workdir: .
    filter_mode: added
    fail_on_error: false
    tool_name: prettier
    prettier_flags: .
```

```
🔄 Running npm install to install prettier...
  npm error code ENOENT
  npm error syscall open
  npm error path /home/runner/work/ansible-role-wine/ansible-role-wine/package.json
  npm error errno -2
  npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/runner/work/ansible-role-wine/ansible-role-wine/package.json'
  npm error enoent This is related to npm not being able to find a file.
  npm error enoent
  npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-05-09T23_16_08_879Z-debug-0.log
  Error: Process completed with exit code 254.
  Warning: Input 'fail_on_error' has been deprecated with message: Deprecated, use `fail_level` instead.
```

Refs: <https://github.com/EPMatt/reviewdog-action-prettier/pull/71>
